services:
  claude-code-proxy:
    container_name: claude-code-proxy
    image: crpi-j9ha7sxwhatgtvj4.cn-shenzhen.personal.cr.aliyuncs.com/koala-ai/claude-code-proxy
    ports:
      - "8080:8080"    # HTTP端口
    environment:
      - ConnectionStrings:DefaultConnection=Data Source=/app/data/ClaudeCodeProxy.db;Cache=Shared
      - RunMigrationsAtStartup=true
      - USER_NAME=admin
      - PASSWORD=admin123
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    build:
      context: .
      dockerfile: src/ClaudeCodeProxy.Host/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
